# Generated by Django 5.1.5 on 2025-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_data',
            field=models.DateTimeField(null=True),
        ),
    ]
