# Generated by Django 3.1.12 on 2025-03-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_due_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
